[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.0", features = ["file_watcher"] }
bevy_framepace = "0.15"
bevy_mod_picking = "0.18"
bevy_eventlistener = "0.7"
common = { path = "../common" }
uuid = "1.0"
ab_glyph = "0.2"

